export {default as BeauticianIConLarge} from './BeauticianIconLarge.svg';
export {default as BeauticianProducts} from './BeauticianProducts.svg';
export {default as BeauticianIconXL} from './BeauticianIconXL.svg';
export {default as BeauticianIconMobile} from './BeauticianIconMobile.svg';
export {default as BeauticianIconMedium} from './BeauticianIconMedium.svg';
export {default as Svgs} from './Svgs';
export {default as GiftCardIcon} from './GiftCardIcon.svg';
export {default as HairDresserIcon} from './HairDresserIcon.svg';
export {default as HairDresserProducts} from './HairDresserProducts.svg';
export {default as LocationIcon} from './LocationIcon.svg';
export {default as ManicureIcon} from './ManicureIcon.svg';
export {default as ManicureProducts} from './ManicureProducts.svg';
export {default as PhoneIcon} from './PhoneIcon.svg';
export {default as PhoneIcon2} from './PhoneIcon2.svg';
export {default as NotFoundIcon} from './NotFoundIcon.svg'
export {default as ErrorIcon} from './ErrorIcon.svg'